// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtyf8yhdvgGATb_XDee3wA2kwBzMQgWz0',
    appId: '1:716931144559:web:e13fe672461f3c78eea69a',
    messagingSenderId: '716931144559',
    projectId: 'shopping-list-e74ca',
    authDomain: 'shopping-list-e74ca.firebaseapp.com',
    storageBucket: 'shopping-list-e74ca.appspot.com',
    measurementId: 'G-D4V4XWRLZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUnyWV99jz2IfMU9DrlLA16PmZx0u59Q',
    appId: '1:716931144559:android:3fd349b9a134e817eea69a',
    messagingSenderId: '716931144559',
    projectId: 'shopping-list-e74ca',
    storageBucket: 'shopping-list-e74ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdxGXHGUyhRcdZ1ngg1qgti1F2gVNhNGc',
    appId: '1:716931144559:ios:222e546bdfa0240beea69a',
    messagingSenderId: '716931144559',
    projectId: 'shopping-list-e74ca',
    storageBucket: 'shopping-list-e74ca.appspot.com',
    iosBundleId: 'com.example.shoppinglist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdxGXHGUyhRcdZ1ngg1qgti1F2gVNhNGc',
    appId: '1:716931144559:ios:222e546bdfa0240beea69a',
    messagingSenderId: '716931144559',
    projectId: 'shopping-list-e74ca',
    storageBucket: 'shopping-list-e74ca.appspot.com',
    iosBundleId: 'com.example.shoppinglist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtyf8yhdvgGATb_XDee3wA2kwBzMQgWz0',
    appId: '1:716931144559:web:2fdd5b02e312ffc2eea69a',
    messagingSenderId: '716931144559',
    projectId: 'shopping-list-e74ca',
    authDomain: 'shopping-list-e74ca.firebaseapp.com',
    storageBucket: 'shopping-list-e74ca.appspot.com',
    measurementId: 'G-C32F9FP1F2',
  );
}
